### ISSUE TITLE
letter spacing issue with after i with Dosis Light

### ISSUE THREAD

**Issue by ajashton** [mapbox/fontnik#2]
I made pbfs for 'Dosis Light, Open Sans Regular' and there's a big space after all the 'i's:

![](http://i.imgur.com/UFJFSok.png)

Dosis font: http://www.fontsquirrel.com/fonts/dosis

**Comment by kkaefer** [comment]
upstream bug: https://github.com/nodebox/opentype.js/pull/56

**Comment by fdb** [comment]
I've fixed the upstream bug, thanks to a pull request from @kkaefer .

**Comment by kkaefer** [comment]
This modules links to the git version of opentype.js anyway, so no need for any changes in here; just update the dependencies.
